[package]
name = "lunatic-process-api"
version = "0.9.2"
edition = "2021"
description = "Lunatic host functions for working with processes."
homepage = "https://lunatic.solutions"
repository = "https://github.com/lunatic-solutions/lunatic/tree/main/crates/lunatic-process-api"
license = "Apache-2.0/MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "^0.8", features = ["v4"] }
anyhow = "^1.0"
wasmtime = "^0.39"
async-std = { version = "^1.0", features = ["attributes", "unstable"] }
hash-map-id = { version = "^0.9", path = "../hash-map-id" }
lunatic-stdout-capture = { version = "^0.9", path = "../lunatic-stdout-capture" }
lunatic-process = { version = "^0.9", path = "../lunatic-process" }
lunatic-common-api = { version = "^0.9", path = "../lunatic-common-api" }
lunatic-error-api = { version = "^0.9", path = "../lunatic-error-api" }
lunatic-wasi-api = { version = "^0.9", path = "../lunatic-wasi-api" }