[package]
name = "lunatic-distributed"
version = "0.9.0"
edition = "2021"
description = "Node to node communication"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
tokio = { version = "^1.14", features = ["macros", "rt-multi-thread", "net", "time", "io-util"] }
serde = { version = "^1.0", features = ["derive"] }
s2n-quic = { version = "1",  default-features = false, features = ["provider-address-token-default", "provider-tls-rustls"] }
bytes = "1"
wasmtime = "^0.37"
dashmap = "5.2.0"
bincode = "^1.3"
log = "^0.4"
async_cell = "0.2.1"
lunatic-process = { version = "^0.9", path = "../lunatic-process" }